# Generated by Django 3.2.14 on 2022-09-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_date',
        ),
    ]
