# Generated by Django 3.2.14 on 2022-08-07 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_remove_membership_image_url'),
        ('profiles', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='memberships.membership'),
        ),
    ]
