# Generated by Django 3.2.14 on 2022-08-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220825_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='membership',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
