# Generated by Django 3.2.14 on 2022-08-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20220827_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street_address2',
        ),
    ]
