# Generated by Django 3.2.14 on 2022-09-06 15:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Booking_Slot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thur'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('duration', models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=3600), '1 hour'), (datetime.timedelta(seconds=5400), '1:30 mins'), (datetime.timedelta(seconds=7200), '2 hours'), (datetime.timedelta(seconds=9000), '2:30 mins'), (datetime.timedelta(seconds=10800), '3 hours')], default=datetime.timedelta(seconds=3600))),
                ('start_hour', models.TimeField(choices=[(datetime.time(5, 0), '05:00'), (datetime.time(6, 0), '06:00'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00')])),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity', to_field='activity_name')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_start_time', models.TimeField(blank=True, null=True)),
                ('booking_end_time', models.DateTimeField(blank=True, null=True)),
                ('booking_slot_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.booking_slot')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', to_field='user')),
            ],
        ),
    ]
