# Generated by Django 3.2.14 on 2022-09-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20220901_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booking_slot',
            options={},
        ),
    ]
