# Generated by Django 3.2.14 on 2022-09-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20220901_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_slot',
            old_name='activity_id',
            new_name='activity',
        ),
    ]
