# Generated by Django 3.2.14 on 2022-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_booking_slot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='booking_slot_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
