# Generated by Django 3.2.14 on 2022-09-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_bookings'),
        ('activities', '0004_rename_activity_id_booking_slot_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
