# Generated by Django 3.2.14 on 2022-09-02 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_activity_booking_slot_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='booking_slot_limit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
