# Generated by Django 3.2.14 on 2022-09-02 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_activity_booking_slot_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_slot',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[('monday', 1), ('tuesday', 2), ('wednesday', 3), ('thursday', 4), ('friday', 5), ('saturday', 6), ('sunday', 7)], validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
