# Generated by Django 3.2.14 on 2022-09-03 17:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_alter_booking_slot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_slot',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thur'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking_slot',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=3600), '1 hour'), (datetime.timedelta(seconds=5400), '1:30 mins'), (datetime.timedelta(seconds=7200), '2 hours'), (datetime.timedelta(seconds=9000), '2:30 mins'), (datetime.timedelta(seconds=10800), '3 hours')], default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='booking_slot',
            name='start_hour',
            field=models.TimeField(choices=[(datetime.time(5, 0), '05:00'), (datetime.time(6, 0), '06:00'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00')]),
        ),
    ]
