# Generated by Django 3.2.14 on 2022-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_booking_slot_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_slot',
            name='end_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
