# Generated by Django 3.2.14 on 2022-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_booking_slot_end_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
