# Generated by Django 3.2.14 on 2022-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20220904_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_slot',
            name='end_hour',
        ),
        migrations.AddField(
            model_name='booking_slot',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
