# Generated by Django 3.2.14 on 2022-08-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20220801_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
