# Generated by Django 3.2.14 on 2022-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
