# Generated by Django 3.2.14 on 2022-07-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
