# Generated by Django 3.2.14 on 2022-08-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_membership_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['number_of_activities']},
        ),
    ]
