# Generated by Django 3.2.14 on 2022-08-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20220826_1055'),
        ('memberships', '0007_remove_membership_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
