# Generated by Django 3.2.14 on 2022-08-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_membership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
